/* automatically generated by ieee754-ops-auto.sh, do not edit! */
#include <tme/common.h>
_TME_RCSID("$Id: ieee754-ops-auto.sh,v 1.5 2009/08/28 01:34:01 fredette Exp $");

/* the IEEE 754 operations: */
struct tme_ieee754_ops {

  /* the version of this structure: */
  tme_uint32_t tme_ieee754_ops_version;

  /* this does a single-precision add: */
  void (*tme_ieee754_ops_single_add) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision sub: */
  void (*tme_ieee754_ops_single_sub) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision mul: */
  void (*tme_ieee754_ops_single_mul) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision div: */
  void (*tme_ieee754_ops_single_div) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision rem: */
  void (*tme_ieee754_ops_single_rem) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision sqrt: */
  void (*tme_ieee754_ops_single_sqrt) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision abs: */
  void (*tme_ieee754_ops_single_abs) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision neg: */
  void (*tme_ieee754_ops_single_neg) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision move: */
  void (*tme_ieee754_ops_single_move) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision rint: */
  void (*tme_ieee754_ops_single_rint) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision cos: */
  void (*tme_ieee754_ops_single_cos) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision acos: */
  void (*tme_ieee754_ops_single_acos) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision cosh: */
  void (*tme_ieee754_ops_single_cosh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision sin: */
  void (*tme_ieee754_ops_single_sin) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision asin: */
  void (*tme_ieee754_ops_single_asin) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision sinh: */
  void (*tme_ieee754_ops_single_sinh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision tan: */
  void (*tme_ieee754_ops_single_tan) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision atan: */
  void (*tme_ieee754_ops_single_atan) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision tanh: */
  void (*tme_ieee754_ops_single_tanh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision atanh: */
  void (*tme_ieee754_ops_single_atanh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision exp: */
  void (*tme_ieee754_ops_single_exp) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision expm1: */
  void (*tme_ieee754_ops_single_expm1) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision log10: */
  void (*tme_ieee754_ops_single_log10) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision log: */
  void (*tme_ieee754_ops_single_log) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision log1p: */
  void (*tme_ieee754_ops_single_log1p) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision getexp: */
  void (*tme_ieee754_ops_single_getexp) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision getman: */
  void (*tme_ieee754_ops_single_getman) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision scale: */
  void (*tme_ieee754_ops_single_scale) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision pow: */
  void (*tme_ieee754_ops_single_pow) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision from-double: */
  void (*tme_ieee754_ops_single_from_double) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision from-extended80: */
  void (*tme_ieee754_ops_single_from_extended80) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision from-quad: */
  void (*tme_ieee754_ops_single_from_quad) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a single-precision from-int32: */
  void (*tme_ieee754_ops_single_from_int32) _TME_P((struct tme_ieee754_ctl *, _tme_const tme_int32_t , struct tme_float *));

  /* this does a single-precision from-int64: */
  void (*tme_ieee754_ops_single_from_int64) _TME_P((struct tme_ieee754_ctl *, _tme_const tme_int64_t , struct tme_float *));

  /* this does a single-precision to-int32: */
  void (*tme_ieee754_ops_single_to_int32) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, tme_int32_t *));

  /* this does a single-precision to-int64: */
  void (*tme_ieee754_ops_single_to_int64) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, tme_int64_t *));

  /* this does a double-precision add: */
  void (*tme_ieee754_ops_double_add) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision sub: */
  void (*tme_ieee754_ops_double_sub) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision mul: */
  void (*tme_ieee754_ops_double_mul) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision div: */
  void (*tme_ieee754_ops_double_div) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision rem: */
  void (*tme_ieee754_ops_double_rem) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision sqrt: */
  void (*tme_ieee754_ops_double_sqrt) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision abs: */
  void (*tme_ieee754_ops_double_abs) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision neg: */
  void (*tme_ieee754_ops_double_neg) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision move: */
  void (*tme_ieee754_ops_double_move) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision rint: */
  void (*tme_ieee754_ops_double_rint) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision cos: */
  void (*tme_ieee754_ops_double_cos) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision acos: */
  void (*tme_ieee754_ops_double_acos) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision cosh: */
  void (*tme_ieee754_ops_double_cosh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision sin: */
  void (*tme_ieee754_ops_double_sin) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision asin: */
  void (*tme_ieee754_ops_double_asin) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision sinh: */
  void (*tme_ieee754_ops_double_sinh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision tan: */
  void (*tme_ieee754_ops_double_tan) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision atan: */
  void (*tme_ieee754_ops_double_atan) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision tanh: */
  void (*tme_ieee754_ops_double_tanh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision atanh: */
  void (*tme_ieee754_ops_double_atanh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision exp: */
  void (*tme_ieee754_ops_double_exp) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision expm1: */
  void (*tme_ieee754_ops_double_expm1) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision log10: */
  void (*tme_ieee754_ops_double_log10) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision log: */
  void (*tme_ieee754_ops_double_log) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision log1p: */
  void (*tme_ieee754_ops_double_log1p) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision getexp: */
  void (*tme_ieee754_ops_double_getexp) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision getman: */
  void (*tme_ieee754_ops_double_getman) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision scale: */
  void (*tme_ieee754_ops_double_scale) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision pow: */
  void (*tme_ieee754_ops_double_pow) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision from-single: */
  void (*tme_ieee754_ops_double_from_single) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision from-extended80: */
  void (*tme_ieee754_ops_double_from_extended80) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision from-quad: */
  void (*tme_ieee754_ops_double_from_quad) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a double-precision from-int32: */
  void (*tme_ieee754_ops_double_from_int32) _TME_P((struct tme_ieee754_ctl *, _tme_const tme_int32_t , struct tme_float *));

  /* this does a double-precision from-int64: */
  void (*tme_ieee754_ops_double_from_int64) _TME_P((struct tme_ieee754_ctl *, _tme_const tme_int64_t , struct tme_float *));

  /* this does a double-precision to-int32: */
  void (*tme_ieee754_ops_double_to_int32) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, tme_int32_t *));

  /* this does a double-precision to-int64: */
  void (*tme_ieee754_ops_double_to_int64) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, tme_int64_t *));

  /* this does a extended80-precision add: */
  void (*tme_ieee754_ops_extended80_add) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision sub: */
  void (*tme_ieee754_ops_extended80_sub) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision mul: */
  void (*tme_ieee754_ops_extended80_mul) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision div: */
  void (*tme_ieee754_ops_extended80_div) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision rem: */
  void (*tme_ieee754_ops_extended80_rem) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision sqrt: */
  void (*tme_ieee754_ops_extended80_sqrt) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision abs: */
  void (*tme_ieee754_ops_extended80_abs) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision neg: */
  void (*tme_ieee754_ops_extended80_neg) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision move: */
  void (*tme_ieee754_ops_extended80_move) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision rint: */
  void (*tme_ieee754_ops_extended80_rint) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision cos: */
  void (*tme_ieee754_ops_extended80_cos) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision acos: */
  void (*tme_ieee754_ops_extended80_acos) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision cosh: */
  void (*tme_ieee754_ops_extended80_cosh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision sin: */
  void (*tme_ieee754_ops_extended80_sin) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision asin: */
  void (*tme_ieee754_ops_extended80_asin) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision sinh: */
  void (*tme_ieee754_ops_extended80_sinh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision tan: */
  void (*tme_ieee754_ops_extended80_tan) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision atan: */
  void (*tme_ieee754_ops_extended80_atan) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision tanh: */
  void (*tme_ieee754_ops_extended80_tanh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision atanh: */
  void (*tme_ieee754_ops_extended80_atanh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision exp: */
  void (*tme_ieee754_ops_extended80_exp) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision expm1: */
  void (*tme_ieee754_ops_extended80_expm1) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision log10: */
  void (*tme_ieee754_ops_extended80_log10) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision log: */
  void (*tme_ieee754_ops_extended80_log) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision log1p: */
  void (*tme_ieee754_ops_extended80_log1p) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision getexp: */
  void (*tme_ieee754_ops_extended80_getexp) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision getman: */
  void (*tme_ieee754_ops_extended80_getman) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision scale: */
  void (*tme_ieee754_ops_extended80_scale) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision pow: */
  void (*tme_ieee754_ops_extended80_pow) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision from-single: */
  void (*tme_ieee754_ops_extended80_from_single) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision from-double: */
  void (*tme_ieee754_ops_extended80_from_double) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision from-quad: */
  void (*tme_ieee754_ops_extended80_from_quad) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a extended80-precision from-int32: */
  void (*tme_ieee754_ops_extended80_from_int32) _TME_P((struct tme_ieee754_ctl *, _tme_const tme_int32_t , struct tme_float *));

  /* this does a extended80-precision from-int64: */
  void (*tme_ieee754_ops_extended80_from_int64) _TME_P((struct tme_ieee754_ctl *, _tme_const tme_int64_t , struct tme_float *));

  /* this does a extended80-precision to-int32: */
  void (*tme_ieee754_ops_extended80_to_int32) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, tme_int32_t *));

  /* this does a extended80-precision to-int64: */
  void (*tme_ieee754_ops_extended80_to_int64) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, tme_int64_t *));

  /* this does a quad-precision add: */
  void (*tme_ieee754_ops_quad_add) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision sub: */
  void (*tme_ieee754_ops_quad_sub) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision mul: */
  void (*tme_ieee754_ops_quad_mul) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision div: */
  void (*tme_ieee754_ops_quad_div) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision rem: */
  void (*tme_ieee754_ops_quad_rem) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision sqrt: */
  void (*tme_ieee754_ops_quad_sqrt) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision abs: */
  void (*tme_ieee754_ops_quad_abs) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision neg: */
  void (*tme_ieee754_ops_quad_neg) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision move: */
  void (*tme_ieee754_ops_quad_move) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision rint: */
  void (*tme_ieee754_ops_quad_rint) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision cos: */
  void (*tme_ieee754_ops_quad_cos) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision acos: */
  void (*tme_ieee754_ops_quad_acos) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision cosh: */
  void (*tme_ieee754_ops_quad_cosh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision sin: */
  void (*tme_ieee754_ops_quad_sin) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision asin: */
  void (*tme_ieee754_ops_quad_asin) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision sinh: */
  void (*tme_ieee754_ops_quad_sinh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision tan: */
  void (*tme_ieee754_ops_quad_tan) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision atan: */
  void (*tme_ieee754_ops_quad_atan) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision tanh: */
  void (*tme_ieee754_ops_quad_tanh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision atanh: */
  void (*tme_ieee754_ops_quad_atanh) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision exp: */
  void (*tme_ieee754_ops_quad_exp) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision expm1: */
  void (*tme_ieee754_ops_quad_expm1) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision log10: */
  void (*tme_ieee754_ops_quad_log10) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision log: */
  void (*tme_ieee754_ops_quad_log) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision log1p: */
  void (*tme_ieee754_ops_quad_log1p) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision getexp: */
  void (*tme_ieee754_ops_quad_getexp) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision getman: */
  void (*tme_ieee754_ops_quad_getman) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision scale: */
  void (*tme_ieee754_ops_quad_scale) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision pow: */
  void (*tme_ieee754_ops_quad_pow) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision from-single: */
  void (*tme_ieee754_ops_quad_from_single) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision from-double: */
  void (*tme_ieee754_ops_quad_from_double) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision from-extended80: */
  void (*tme_ieee754_ops_quad_from_extended80) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, struct tme_float *));

  /* this does a quad-precision from-int32: */
  void (*tme_ieee754_ops_quad_from_int32) _TME_P((struct tme_ieee754_ctl *, _tme_const tme_int32_t , struct tme_float *));

  /* this does a quad-precision from-int64: */
  void (*tme_ieee754_ops_quad_from_int64) _TME_P((struct tme_ieee754_ctl *, _tme_const tme_int64_t , struct tme_float *));

  /* this does a quad-precision to-int32: */
  void (*tme_ieee754_ops_quad_to_int32) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, tme_int32_t *));

  /* this does a quad-precision to-int64: */
  void (*tme_ieee754_ops_quad_to_int64) _TME_P((struct tme_ieee754_ctl *, _tme_const struct tme_float *, tme_int64_t *));
};

/* the strict compliance operations: */
extern _tme_const struct tme_ieee754_ops tme_ieee754_ops_strict;

/* the partial compliance operations: */
extern _tme_const struct tme_ieee754_ops tme_ieee754_ops_partial;

/* the unknown compliance operations: */
extern _tme_const struct tme_ieee754_ops tme_ieee754_ops_unknown;
